before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: BQV/5T0ZnJb/pUXzFNlF5BoeaQ6GPLL3py+nRyYRvBZF4sVAE9/VClgf3TjHCw/0fcFX720W0D0u7064FdDbf40Z3p0Jzk67u1oSCxT9qbvyNZvxgmTlpY727Fo4WJgtUJmQHjJCvNMyBH9O+2dv4F/zP2oqAZqfTvcI5nroAtokxSeFlB8Wzj/tQyQPQjVBhq86prg3ij/QQSstiPcK8jKOKoBi1R5a2QDJDXCxN8ozZgbTB7h6IEjObYH/yGaIf4tZLZm+a60RQ/y7OHoaX1/ku4IKB2qDjhBYNr+QMIFbWQbtFTVQYu132cY+vFwWPE0nYhOuhfzNs6dyGd7pHF+Oa+aTJzPx7XWamElJerIhkaf+y++vq9LBTTifblLLCLK040N+dn1+1hB3tCONEXRFm5IgFeBV8x1KbutHf9n2FhKpQBfKkTq0vV0ocaIVTcKYxK+0n4M/zcnK2iKQ3rKjcHOAHsXvoQCCI+86ZVAneraxogXd+GRUtn+t+8E6z7gM1ESnz78BTbUYn//qdEB7NRMX+tj4GAPyPH8oTF2zTOK9QAKuW4cNumlXP0N7XE0WEXRnu69Vp08BW+8FYzvASoVdgHdFlC8B+bTVTZAbN6vEERAXMmg+60jjGpdr7ZyRoqtTAYiqEsGfn4Ex3Tq7uK79rah8aPv89K0HMLs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
